#
name: Build and Test

on:
  push:  # Triggers the workflow on push events to any branch
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      branch:
        description: "Branch to build and test"
        required: true
        default: "main"

jobs:
  buildServer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Build Server Solution
        run: |
          cd Server
          dotnet restore
          dotnet build -c Release

  test-server:
    needs: buildServer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Run Unit Tests with Coverage
        run: |
          cd Server
          dotnet test Server.Test/Server.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../coverage/unit-tests.xml /p:ExcludeByFile=\"**/Migrations/*,**/Program.cs,**/Models/*,**/Data/*,\" /p:ExcludeByAttribute="TestSDKAutoGeneratedCode"

      - name: Run Integration Tests with Coverage
        run: |
          cd Server
          dotnet test Server.IntegrationTest/Server.IntegrationTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../coverage/integration-tests.xml /p:ExcludeByFile=\"**/Migrations/*,**/Program.cs,**/Models/*,**/Data/*,\" /p:ExcludeByAttribute="TestSDKAutoGeneratedCode"

      - name: Install ReportGenerator Tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator "-reports:Server/coverage/*.xml" "-targetdir:Server/coverage/CoverageReport" "-reporttypes:Html"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-unittest
          path: Server/coverage/CoverageReport/
